### PR TITLE
Update org.rncbc.qpwgraph.yml

### PR DESCRIPTION
**Pull request by rncbc**
A tenth beta release (v0.3.2)

### CODE REVIEW

**Comment by travier** [comment]
Freedesktop GitLab having troubles:
```
• url-not-found         : <screenshot> failed to download (HTTP 504: Gateway Timeout) [https://gitlab.freedesktop.org/rncbc/qpwgraph/-/raw/main/src/images/qpwgraph_screenshot-1.png]
• url-not-found         : <screenshot> failed to download (HTTP 504: Gateway Timeout) [https://gitlab.freedesktop.org/rncbc/qpwgraph/-/raw/main/src/images/qpwgraph.svg]
```

**Comment by hfiguiere** [comment]
From the info I gathered, it's a disk problem (no dataloss) that make the cluster working in a degraded mode.

**Comment by hfiguiere** [comment]
it seems to be back online

bot, build

**Comment by rncbc** [comment]
gitlab.freedesktop.org seems to be back online
closing now

**Pull request closed without merging**
